#ifndef APP_CONSTANTS_H
#define APP_CONSTANTS_H

#define DAILY_DECREMENT -1
#define STARTING_SCORE 10

typedef enum { GENERIC_TAG, NEW_COMMENT_UPDATE, DECREMENT_UPDATE} tag_t;

typedef enum {
    MASTER, POST_MANAGER, COMMENT_MANAGER, OUT_MANAGER
} process_t;

#endif
